### ISSUE TITLE
on_socket_response interaction type 

### ISSUE THREAD

**Issue by Beastman9095** [kiki7000/discord.py-components#26]
Bug with `on_socket_response` possibly caused by interaction type not being checked? 

When the library is used alongside the discord-py-slash-command library console gets an error output with the following.

Issue used to be occurring in discord-py-slash-command library as well but it has been fixed with the latest version on their end allowing buttons to work. 

```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_components\client.py", line 79, in on_socket_response
    event = self._events.get(res["d"]["data"]["component_type"], None)
KeyError: 'component_type'
```

**Comment by Beastman9095** [comment]
Newer error

```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_components\client.py", line 78, in on_socket_response
    ctx = self._get_context(res)
  File "C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_components\client.py", line 345, in _get_context
    data = self._structured_raw_data(json)
  File "C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_components\client.py", line 316, in _structured_raw_data
    for line in raw_data["message"]["components"]:
KeyError: 'message'
```

**Comment by Shaqalito** [comment]
same thing
 `Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_components/client.py", line 80, in on_socket_response
    ctx = self._get_context(res)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_components/client.py", line 342, in _get_context
    data = self._structured_raw_data(json)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_components/client.py", line 310, in _structured_raw_data
    if "components" not in raw_data["message"]:
KeyError: 'message'`

**Comment by kiki7000** [comment]
Could you show me the code?

**Comment by kiki7000** [comment]
Seems like it is resolved :)
