### ISSUE TITLE
[Bug] Module is breaking Replies

### ISSUE THREAD

**Issue by Greekfire26** [kiki7000/discord.py-components#27]
When including `ddb = DiscordComponents(client)` anywhere in code that also uses `ctx.reply()` results in the following error: 

```
Ignoring exception in command test_button:
Traceback (most recent call last):
  File "C:\Users\nsalo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\nsalo\Documents\Dev\Python\104th\Admin Bot\main.py", line 30, in test_button
    await ctx.send("Test complete!", reference=ctx.message)
  File "C:\Users\nsalo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_components\client.py", line 65, in send_component_msg_prop
    return await self.send_component_msg(ctxorchannel.channel, *args, **kwargs)
  File "C:\Users\nsalo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_components\client.py", line 187, in send_component_msg
    data = await self.bot.http.request(
  File "C:\Users\nsalo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "C:\Users\nsalo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "C:\Users\nsalo\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\nsalo\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\nsalo\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\nsalo\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Message is not JSON serializable
```

when I remove `ddb = DiscordComponents(client)` or use `ctx.send` instead of `ctx.reply` the issue is fixed.

**Comment by kiki7000** [comment]
Fixed on 0.4.9
