### ISSUE TITLE
[Bug] A KeyError is raised every time a message is sent. (Even when there is no component in it and the component library is not used at all)

### ISSUE THREAD

**Issue by Shaqalito** [kiki7000/discord.py-components#57]
## Excpected Action
> Send a message

## Actual Action
> Raises an error
```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_components/client.py", line 80, in on_socket_response
    ctx = self._get_context(res)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_components/client.py", line 355, in _get_context
    data = self._structured_raw_data(json)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_components/client.py", line 323, in _structured_raw_data
    if "components" not in raw_data["message"]:
KeyError: 'message'
```

## Reproducing the action
```
@slash.slash(name="Muted", description="Voir les utilisateurs Mutés", guild_ids= guild_id)
async def muted(ctx):
  staff_roles= (get(ctx.guild.roles, id=754983704018812938), get(ctx.guild.roles, id=844653071203827754))
  if any(staff_role in ctx.author.roles for staff_role in staff_roles):
    with open("muted_users.json", "r") as f:
      global muted_users_list
      muted_users_list= []
      muted_users = json.load(f)

      for value in muted_users.values():
        muted_users_list.append(value)

      final_list = str(muted_users_list)
      final_list = final_list.replace(",", "\n")
      final_list = final_list.replace("[", "")
      final_list = final_list.replace("]", "")
      final_list = final_list.replace("'", "")
      if final_list == "":
        final_list = "Aucun utilisateur n'est mute."
        em= Embed(title= "Muted Users", description= final_list, color= 0xFF5BF8)
        msg = await ctx.send(embed= em)

      else:
        msg = await ctx.send("᲼")
        ctx = await client.get_context(msg)
      
        em= Embed(title= "Muted Users", description= final_list, color= 0xFF5BF8)

        await ctx.send(embed= em, components=[
      Button(label= "Unmute All", style=4, id="clear_muted_button"),
    ])

        while True:
          res = await client.wait_for("button_click")
          if res.component.id == "clear_muted_button":
            print("clicked muted")
            with open("muted_users.json", "r") as f:
              muted_users = json.load(f)

              for key in muted_users.keys():
                for i in range(0, len(muted_users.keys())):
                  user = ctx.guild.get_member(int(key))
                  await ctx.invoke(client.get_command("unmute"), target=user)


            confem = Embed(title= "Tous les mutes ont été retirés", color= 0xFF5BF8)

            await res.respond(type=4, embed= confem)
```

## Possible Solution
> Idk but I hope you can find one :D

## Environment
> Python 3.8.2

## Check
- [x] Are you using the newest version?
- [ ] Does this bug occurs security issues?
- [x] Do I admire @kiki7000 for how hard he works ?

**Comment by GingerGigiCat** [comment]
https://github.com/kiki7000/discord.py-components/issues/58#issuecomment-850972640
What did you do that made it work?

**Comment by Shaqalito** [comment]
Add me on discord. The error I tali about here is not fatal btw it's going to be here until the compatibilities issues are fixed

**Comment by GingerGigiCat** [comment]
@Shaqalito I sent you a DM
